#!/bin/bash -e

# Note: dash does not support redirecting file descriptors above 9,
# but ganeti typically passes 11. Hence this must be run under bash.
# https://bugs.launchpad.net/ubuntu/+source/dash/+bug/249620

if test -n "$EXP_SIZE_FD"; then
  blockdev --getsize64 "$EXPORT_DEVICE" >&"$EXP_SIZE_FD"
fi

dd if="$EXPORT_DEVICE" bs=1048576
